package io.github.hiwepy.opencli.registry;

import java.util.Collections;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * 文档 index 中的 Browser / Desktop 分类（由脚本生成）。
 */
public final class OpenCliAdapterTaxonomy {

    private OpenCliAdapterTaxonomy() {
    }

    /** Desktop 适配器 id 列表（固定集）。 */
    public static final List<String> DESKTOP_IDS = Collections.unmodifiableList(Arrays.asList(
        "antigravity",
        "chatgpt-app",
        "chatwise",
        "codex",
        "cursor",
        "discord-app",
        "doubao-app",
        "qoder",
        "trae-cn",
        "trae-solo"
    ));

    /** Browser 文档链接中的适配器 id。 */
    public static final List<String> BROWSER_IDS = Collections.unmodifiableList(Arrays.asList(
        "12306",
        "1688",
        "1point3acres",
        "36kr",
        "51job",
        "aibase",
        "amazon",
        "apple-podcasts",
        "archive",
        "arxiv",
        "autohome",
        "baidu-scholar",
        "band",
        "barchart",
        "bbc",
        "bilibili",
        "binance",
        "bloomberg",
        "bluesky",
        "booking",
        "boss",
        "brave",
        "chaoxing",
        "chatgpt",
        "chess",
        "claude",
        "cnki",
        "coingecko",
        "confluence",
        "coupang",
        "crates",
        "ctrip",
        "dblp",
        "deepseek",
        "defillama",
        "devto",
        "dianping",
        "dictionary",
        "dockerhub",
        "dongchedi",
        "douban",
        "doubao",
        "douyin",
        "duckduckgo",
        "eastmoney",
        "endoflife",
        "facebook",
        "flathub",
        "flomo",
        "gemini",
        "geogebra",
        "gitee",
        "github",
        "github-trending",
        "google",
        "google-scholar",
        "goproxy",
        "gov-law",
        "gov-policy",
        "grok",
        "guazi",
        "hackernews",
        "hf",
        "hltv",
        "homebrew",
        "huodongxing",
        "hupu",
        "imdb",
        "indeed",
        "instagram",
        "jd",
        "jianyu",
        "jike",
        "jimeng",
        "jira",
        "juejin",
        "ke",
        "kimi",
        "lesswrong",
        "lichess",
        "linkedin",
        "linkedin-learning",
        "linux-do",
        "lobsters",
        "maimai",
        "manus",
        "maven",
        "mdn",
        "medium",
        "mercury",
        "mubu",
        "notebooklm",
        "nowcoder",
        "npm",
        "nuget",
        "nvd",
        "oeis",
        "ones",
        "openalex",
        "openfda",
        "openreview",
        "osv",
        "packagist",
        "paperreview",
        "pixiv",
        "powerchina",
        "producthunt",
        "pubmed",
        "pypi",
        "quark",
        "qwen",
        "reddit",
        "rednote",
        "rest-countries",
        "reuters",
        "rfc",
        "rubygems",
        "semanticscholar",
        "sinablog",
        "sinafinance",
        "slock",
        "smzdm",
        "spotify",
        "stackoverflow",
        "steam",
        "substack",
        "suno",
        "taobao",
        "tdx",
        "ths",
        "tieba",
        "tiktok",
        "toutiao",
        "tvmaze",
        "twitter",
        "uisdc",
        "uiverse",
        "upwork",
        "v2ex",
        "wanfang",
        "web",
        "wechat-channels",
        "weibo",
        "weixin",
        "weread",
        "weread-official",
        "wikidata",
        "wikipedia",
        "wttr",
        "xianyu",
        "xiaoe",
        "xiaohongshu",
        "xiaoyuzhou",
        "xueqiu",
        "yahoo",
        "yahoo-finance",
        "yollomi",
        "youdao",
        "youtube",
        "yuanbao",
        "zhihu",
        "zlibrary",
        "zsxq"
    ));

    private static final Set<String> DESKTOP_ID_SET = new HashSet<>(DESKTOP_IDS);

    /**
     * @param adapterId OpenCLI adapter id
     * @return 是否属于 Desktop 表
     */
    public static boolean isDesktopAdapter(String adapterId) {
        return adapterId != null && DESKTOP_ID_SET.contains(adapterId);
    }
}
